export { default as lightIcon } from '../assets/light.svg'
export { default as heroImg } from '../assets/hero.jpg'
export { default as spiral } from '../assets/images/spiral.png'
export { default as banner } from '../assets/images/banner.jpg'
export { default as first_section } from '../assets/images/first-section.jpg'

export { default as first } from '../assets/images/slider/first.jpg'
export { default as second } from '../assets/images/slider/second.svg'
export { default as third } from '../assets/images/slider/third.jpg'
export { default as fourth } from '../assets/images/slider/fourth.svg'
export { default as fifth } from '../assets/images/slider/fifth.jpg'
export { default as sixth } from '../assets/images/slider/sixth.jpg'
export { default as seventh } from '../assets/images/slider/seventh.jpg'
export { default as ninth } from '../assets/images/slider/ninth.jpg'
export { default as tenth } from '../assets/images/slider/tenth.jpg'
export { default as eleventh } from '../assets/images/slider/eleventh.jpg'